GET http://localhost:8000/products/ HTTP/1.1

###
GET http://localhost:8000/product/1/ HTTP/1.1

###
PUT http://localhost:8000/product/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MDI4NjYxLCJpYXQiOjE3MzUwMjgzNjEsImp0aSI6IjZmN2U5NDM5MzdkMTQ2YWFiNzI0NTM1NmU5Mzg1YmI0IiwidXNlcl9pZCI6Mn0.d2xkfS2RTogxbVeIdY8EbrZCDcIwlNN7bS1QOd450XQ

{
    "name":"Television",
    "price":100.00,
    "stock":15,
    "description": "An TV"
}

###
DELETE http://localhost:8000/product/1/ HTTP/1.1

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MDI1MDgwLCJpYXQiOjE3MzUwMjQ3ODAsImp0aSI6IjNkYmVmNTkzOGNhMDQ5NWZiNmJmZjA4N2U5N2QwOGQ0IiwidXNlcl9pZCI6Mn0.9TFSZ8Km50g9S1e8SCR4zFnI2BrHCqkKdZdZrC3IhQQ

{
    "name":"TV5",
    "price":100.00,
    "stock":15,
    "description": "An TV"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "pythondev",
    "password": "python12345"
}

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNTExMjY3MCwiaWF0IjoxNzM1MDI2MjcwLCJqdGkiOiJjZjBhNzI1ZGY2ODY0NWQxOTcwYTQ3NTFkY2Q0NmU1OSIsInVzZXJfaWQiOjJ9.FMnZz0V_QN5BxkomgWZGfMSyc2c8DdCX-dLanGbHCK4"
}

###
GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1MDI1NDQ3LCJpYXQiOjE3MzUwMjUxNDcsImp0aSI6IjhmMjRhZDRmYWVjZDQ2ZjY5OWNiODVkZDM3YjcxYzYzIiwidXNlcl9pZCI6Mn0.gkIgSSiqmZxE7o6J2HtT-l7sKvitqqnt0NUhkekLryM